config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root "home#index"
  get 'home/makerequest', to: "home#makerequest", as: 'makerequest'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require 'open-uri'
	require 'nokogiri'
	require 'cgi'

  before_action :set_url_params, only: [:makerequest]
  def index  	
  end
  def makerequest
  	respond_to do |format|
  		format.html{
  			doc = Nokogiri::HTML(open(set_url_params[:instaurl]))
  			if !(doc.blank?)
          @postData = Hash.new
          @postData[:author] = CGI.parse(URI.parse(set_url_params[:instaurl]).query)["taken-by"].join if set_url_params[:instaurl].include? 'taken-by'
          @postData[:link] = doc.at("meta[property='og:url']")["content"]
          @postData[:description] = doc.at("meta[property='og:description']")["content"]
          if (doc.at("meta[name='medium']")["content"] == "image")                        
            @postData[:imgUrl] = doc.at("meta[property='og:image']")["content"]
          elsif (doc.at("meta[name='medium']")["content"] == "video")            
            @postData[:videoUrl] = doc.at("meta[property='og:video:secure_url']")["content"]            
          end
        end
  		}
  		format.js{
  			doc = Nokogiri::HTML(open(set_url_params[:instaurl]))
  			if !(doc.blank?)
          @postData = Hash.new
          @postData[:author] = CGI.parse(URI.parse(set_url_params[:instaurl]).query)["taken-by"].join if set_url_params[:instaurl].include? 'taken-by'
          @postData[:link] = doc.at("meta[property='og:url']")["content"]
          @postData[:description] = doc.at("meta[property='og:description']")["content"]
          if (doc.at("meta[name='medium']")["content"] == "image")                        
            @postData[:imgUrl] = doc.at("meta[property='og:image']")["content"]
          elsif (doc.at("meta[name='medium']")["content"] == "video")            
            @postData[:videoUrl] = doc.at("meta[property='og:video:secure_url']")["content"]            
          end
        end
  		}
  	end  	  	
  end

  private

  def set_url_params
  	params.require(:url).permit(:instaurl)		  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_response.html.erb
<div class="info-wrapper">
	<div class="image_video-wrapper">
		<% if (@postData.key?(:imgUrl)) %>
			<%= image_tag(@postData[:imgUrl]) %>
		<% elsif (@postData.key?(:videoUrl)) %>
			<video width="350" controls>
			  <source src="<%= @postData[:videoUrl] %>" type="video/mp4">  
			  Your browser does not support HTML5 video.
			</video>
		<% end %>				
	</div>
	<div class="content-wrapper">
	<% if @postData.key?(:author) %>
		<div class="element author">
			<label>Autor: </label>
			<h3><%= link_to "@#{@postData[:author]}", "https://www.instagram.com/#{@postData[:author]}", target: :"_blank" %></h3>
		</div>	
	<% end %>
	
		<div class="element link">
			<label>Link do Instagram: </label>
			<%= link_to @postData[:link], @postData[:link], target: :"_blank" %>
		</div>
	
		<div class="element download">		
			<%= link_to "Download", @postData.key?(:imgUrl) ? @postData[:imgUrl] : @postData[:videoUrl], target: :"_blank"  %>
		</div>	
	</div>	
</div>

app/views/home/index.html.erb
<div class="form-container">
	<header class="brand">
		<h1><small>i</small>Download</h1>
	</header>
	<section class="the-form">
		<%= simple_form_for(:url, :url => makerequest_path , :action => :makerequest, :multipart => true, :method => :get ,remote: true ) do |f| %>
			<%= f.input :instaurl,:wrapper => false , input_html:{:placeholder => 'https://www.instagram.com/p/BiPMOexntUC/', type: :text, autofocus: true, autocomplete: :off}, :label => "url do instagram" %>
			<%= f.button :submit, 'Buscar' %>
		<% end %>		
	</section>
</div>
<div id="rcontainer" class="results-container">	
</div>

 

app/views/home/makerequest.js.erb
$('#rcontainer').append("<%= j render partial: 'home/response', :locals => @postData  %>").slideDown(200, function(){
	$("#url_instaurl").val('');
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Idownload - Download your photos or Videos from instagram link</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0' name='viewport'>
  <link rel="apple-touch-icon" sizes="57x57" href="/assets/favicon/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="/assets/favicon/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/assets/favicon/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/assets/favicon/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/assets/favicon/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/assets/favicon/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="/assets/favicon/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/assets/favicon/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="/assets/favicon/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192"  href="/assets/favicon/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="/assets/favicon/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon/favicon-16x16.png">
	<link rel="manifest" href="/assets/favicon/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="/assets/favicon/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">
  <%= csrf_meta_tags %>
</head>
<body>	
	<div class="container-fluid">
		<div class="bgwrapper">		
			<div class="main-content">
				<%= yield %>
			</div>			
			<div class="bg-overlay"></div>
			<footer class="copyright">				
					© 2018 <a href="http://www.krotedev.com.br" target="_blank">KröteDev</a> | Imagens: <a href="http://unsplash.com/" target="_blank" >Unsplash</a>				
			</footer>
		</div>	
	</div>
</body>
</html>
                                                                              